
import com.sun.istack.internal.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import java.util.Vector;
import java.util.logging.Level;
//import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Souvik
 */
public class bookinfo extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public bookinfo() {
        super("book info");
        initComponents();
        conn=javaconnect.ConnerDb();
        book_load();
    }
     public void book_load()
     {
         int c;
         try{
             pst=conn.prepareStatement("select * from bookinfo");
             rs=pst.executeQuery();
             ResultSetMetaData rsd=rs.getMetaData();
             c=rsd.getColumnCount();
             DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
             d.setRowCount(0);
             while(rs.next())
             {
                 Vector v2=new Vector();
                 for(int i=1;i<=c;i++)
                 {
                     v2.add(rs.getString("bookid"));
                     v2.add(rs.getString("name"));
                     v2.add(rs.getString("edition"));
                     v2.add(rs.getString("publisher"));
                     v2.add(rs.getString("price"));
                     v2.add(rs.getString("pages"));
                 }
                 d.addRow(v2);
             }
         }catch(SQLException ex){
            // Logger.getLogger(bookinfo.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(this, ex);
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("book id");

        jLabel2.setText("name");

        jLabel3.setText("edition");

        jLabel4.setText("publisher");

        jLabel5.setText("price");

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("deleete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("pages");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "book_id", "name", "edition", "publisher", "price", "pages"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(153, 153, 153)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      /* DefaultTableModel tblModel= (DefaultTableModel)jTable1.getModel();
       String tblId=tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
       String tblName=tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
       String tblEdition=tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
       String tblPublisher=tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
       String tblPrice=tblModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
       String tblPages=tblModel.getValueAt(jTable1.getSelectedRow(), 5).toString();
       //set to text field
       jTextField1.setText(tblId);
       jTextField2.setText(tblName);
       jTextField3.setText(tblEdition);
       jTextField4.setText(tblPublisher);
       jTextField5.setText(tblPrice);
       jTextField6.setText(tblPages);*/
      DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
      int selectIndex=jTable1.getSelectedRow();
      int id=Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
      jTextField1.setText(d1.getValueAt(selectIndex,0).toString());
      jTextField2.setText(d1.getValueAt(selectIndex,1).toString());
      jTextField3.setText(d1.getValueAt(selectIndex,2).toString());
      jTextField4.setText(d1.getValueAt(selectIndex,3).toString());
      jTextField5.setText(d1.getValueAt(selectIndex,4).toString());
      jTextField6.setText(d1.getValueAt(selectIndex,5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
      int selectIndex=jTable1.getSelectedRow();
      int id=Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
        String bookid=jTextField1.getText();
        String name=jTextField2.getText();
        String edition=jTextField3.getText();
        String publisher=jTextField4.getText();
        String price=jTextField5.getText();
        String pages=jTextField6.getText();
        try{
            pst=conn.prepareStatement("update bookinfo set name=?,edition=?,publisher=?,price=?,pages=? where bookid=?");
            //pst.setString(0, bookid);
             pst.setString(1, name);
              pst.setString(2, edition);
               pst.setString(3, publisher);
                pst.setString(4,price);
                 pst.setString(5,pages);
                 pst.setInt(6, id);
            int k= pst.executeUpdate();
            if(k==1)
            {
             JOptionPane.showMessageDialog(this, "value updated");
             jTextField1.setText(" ");
             jTextField2.setText(" ");
             jTextField3.setText(" ");
             jTextField4.setText(" ");
             jTextField5.setText(" ");
             jTextField6.setText(" ");
             jTextField1.requestFocus();
              book_load();
            }
            else
            {
               JOptionPane.showMessageDialog(this, "error");
            }
                 
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        } /*  DefaultTableModel tblModel= (DefaultTableModel)jTable1.getModel();
      if(jTable1.getSelectedRowCount()==1){
          String id=jTextField1.getText();
          String name=jTextField2.getText();
          String edition=jTextField3.getText();
          String publisher=jTextField4.getText();
          String price=jTextField5.getText();
          String pages=jTextField6.getText();
          
          //set update value on  table row
          tblModel.setValueAt(id, jTable1.getSelectedRow(), 0);
          tblModel.setValueAt(name, jTable1.getSelectedRow(), 1);
          tblModel.setValueAt(edition, jTable1.getSelectedRow(), 2);
          tblModel.setValueAt(publisher, jTable1.getSelectedRow(),3);
          tblModel.setValueAt(price, jTable1.getSelectedRow(), 4);
          tblModel.setValueAt(pages, jTable1.getSelectedRow(), 5);
          //update message display
          JOptionPane.showMessageDialog(this, "updated successfully");
               
      } else{
          if(jTable1.getRowCount()==0){
              JOptionPane.showMessageDialog(this, "table is empty");
          }else{
              JOptionPane.showMessageDialog(this, "please select a row for update");
          }
      }*/      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        homepage ob= new homepage();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bookid=jTextField1.getText();
        String name=jTextField2.getText();
        String edition=jTextField3.getText();
        String publisher=jTextField4.getText();
        String price=jTextField5.getText();
        String pages=jTextField6.getText();
        try{
            pst=conn.prepareStatement("insert into bookinfo(bookid,name,edition,publisher,price,pages)values(?,?,?,?,?,?)");
            pst.setString(1, bookid);
             pst.setString(2, name);
              pst.setString(3, edition);
               pst.setString(4, publisher);
                pst.setString(5,price);
                 pst.setString(6,pages);
            int k= pst.executeUpdate();
            if(k==1)
            {
             JOptionPane.showMessageDialog(this, "book inserted");
             jTextField1.setText(" ");
             jTextField2.setText(" ");
             jTextField3.setText(" ");
             jTextField4.setText(" ");
             jTextField5.setText(" ");
             jTextField6.setText(" ");
             jTextField1.requestFocus();
              book_load();
            }
            else
            {
               JOptionPane.showMessageDialog(this, "error");
            }
                 
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
      int selectIndex=jTable1.getSelectedRow();
      int id=Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
       /* String bookid=jTextField1.getText();
        String name=jTextField2.getText();
        String edition=jTextField3.getText();
        String publisher=jTextField4.getText();
        String price=jTextField5.getText();
        String pages=jTextField6.getText();*/
        try{
            pst=conn.prepareStatement("delete from student where studentid=?");
            //pst.setString(0, bookid);
             /*pst.setString(1, name);
              pst.setString(2, edition);
               pst.setString(3, publisher);
                pst.setString(4,price);
                 pst.setString(5,pages);*/
                 pst.setInt(1, id);
            int k= pst.executeUpdate();
            if(k==1)
            {
             JOptionPane.showMessageDialog(this, "book deleted");
             jTextField1.setText(" ");
             jTextField2.setText(" ");
             jTextField3.setText(" ");
             jTextField4.setText(" ");
             jTextField5.setText(" ");
             jTextField6.setText(" ");
             jTextField1.requestFocus();
              book_load();
            }
            else
            {
               JOptionPane.showMessageDialog(this, "error");
            }
                 
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        //get jtable model first
       /* DefaultTableModel tblModel= (DefaultTableModel)jTable1.getModel();
        //delete row
        if(jTable1.getSelectedRowCount()==1){
            tblModel.removeRow(jTable1.getSelectedRow());
        }else{
            if(jTable1.getRowCount()==0){
                //if table is empty show this message
                JOptionPane.showMessageDialog(this, "table is empty");
            }else{
                //if no row is selected then show this message
                JOptionPane.showMessageDialog(this, "please select a single row");
            }
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
